# Generated by Django 5.1.4 on 2025-01-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot_contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_id",
            field=models.CharField(default="", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
