# Generated by Django 5.1.4 on 2025-01-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot_contact", "0002_contact_contact_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
