# Generated by Django 5.1.6 on 2025-02-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot_contact", "0005_contact_created_at_contact_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="availability",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="skills",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
