# Generated by Django 5.1.6 on 2025-02-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_contact', '0007_contact_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
