# Generated by Django 5.1.6 on 2025-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot_contact", "0009_alter_contact_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
